# Generated by Django 3.0.5 on 2022-07-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
