# Generated by Django 3.0.5 on 2022-07-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
    ]
